#!/usr/bin/env python3
"""Stamp the shared nav/footer partials into every page of the site.

The partials in partials/ are the single source of truth. Edit those, run this
script, commit the result. CI (.github/workflows/check-partials.yml) re-runs it
with --check and fails the PR if any page has drifted.

  python3 tools/build-nav.py            # rewrite pages in place
  python3 tools/build-nav.py --check    # exit 1 if any page is out of date

apply.html / enroll.html / join.html are deliberately excluded: they are
distraction-free conversion landing pages that carry no nav and no footer at
all, so a visitor has no way out of the funnel except the form.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Landing pages that intentionally carry no site chrome at all - no nav, no
# footer. Do not stamp anything into these.
EXCLUDE = {"apply.html", "enroll.html", "join.html"}

# Which nav entries get class="active" on which page.
ACTIVE = {
    "how-it-works.html": ["how"],
    "leaderboard.html": ["proof", "leaderboard"],
    "self-paced-leaderboard.html": ["proof", "self-paced"],
    "foundation-leaderboard.html": ["proof", "foundation"],
    "champion.html": ["proof", "champion"],
    "graduates.html": ["proof", "graduates"],
    "alumni.html": ["proof", "alumni"],
    "stories.html": ["proof", "stories"],
    "placement.html": ["proof", "placement"],
    "enterprise.html": ["enterprise"],
    "campus.html": ["campus"],
}

UNIVERSITY_DEFAULT = "https://university.pravinmishra.com/?utm_source=dmi&amp;utm_medium={medium}"
# Every page points at the storefront root. self-paced-leaderboard.html used to
# point at the self-paced product page instead; normalised 2026-08-22.
UNIVERSITY_OVERRIDE: dict[str, str] = {}

NAV_RE = re.compile(r"<nav id=\"navbar\">.*?</nav>", re.DOTALL)
FOOTER_RE = re.compile(r"<footer>.*?</footer>", re.DOTALL)


def set_active(html: str, key: str) -> str:
    """Add class="active" to the <a> carrying data-nav="key"."""
    pattern = re.compile(r"<a\b[^>]*\bdata-nav=\"" + re.escape(key) + r"\"[^>]*>")

    def repl(match: re.Match) -> str:
        tag = match.group(0)
        if 'class="' in tag:
            return tag.replace('class="', 'class="active ', 1)
        return tag.replace("<a ", '<a class="active" ', 1)

    return pattern.sub(repl, html)


def render(partial: str, *, prefix: str, medium: str, university: str,
           active_keys: list[str]) -> str:
    out = (partial
           .replace("{{ROOT}}", prefix)
           .replace("{{UNIVERSITY}}", university)
           .replace("{{MEDIUM}}", medium))
    for key in active_keys:
        out = set_active(out, key)
    return out


def pages():
    """Yield (path, prefix, nav_medium, footer_medium) for every page to stamp."""
    for path in sorted(ROOT.glob("*.html")):
        if path.name not in EXCLUDE:
            yield path, "", "nav", "footer"
    for path in sorted(ROOT.glob("blog/*.html")):
        yield path, "../", "nav", "footer"
    for path in sorted(ROOT.glob("s/*.html")):
        yield path, "../", "cert-page", "badge-page"


def main() -> int:
    check = "--check" in sys.argv
    nav_partial = (ROOT / "partials" / "nav.html").read_text().rstrip("\n")
    footer_partial = (ROOT / "partials" / "footer.html").read_text().rstrip("\n")

    stale_core, stale_badges, written = [], [], 0

    for path, prefix, nav_medium, footer_medium in pages():
        original = path.read_text()
        updated = original
        rel = path.relative_to(ROOT).as_posix()
        active_keys = ["blog"] if rel.startswith("blog/") else ACTIVE.get(path.name, [])

        if NAV_RE.search(updated):
            university = UNIVERSITY_OVERRIDE.get(
                path.name, UNIVERSITY_DEFAULT.format(medium=nav_medium))
            nav = render(nav_partial, prefix=prefix, medium=nav_medium,
                         university=university, active_keys=active_keys)
            updated = NAV_RE.sub(lambda _: nav, updated, count=1)

        if FOOTER_RE.search(updated):
            footer = render(footer_partial, prefix=prefix, medium=footer_medium,
                            university="", active_keys=[])
            updated = FOOTER_RE.sub(lambda _: footer, updated, count=1)

        if updated == original:
            continue

        if check:
            (stale_badges if rel.startswith("s/") else stale_core).append(rel)
        else:
            path.write_text(updated)
            written += 1

    if not check:
        print(f"Stamped nav/footer into {written} page(s).")
        return 0

    # Badge pages under s/ are regenerated by the dmi-review-agent repo. Report
    # drift there, but never fail on it — a hard failure would block that repo's
    # auto-merged daily leaderboard PRs.
    if stale_badges:
        print(f"WARNING: {len(stale_badges)} badge page(s) under s/ differ from "
              f"the partials. Update review_agent/badges.py in dmi-review-agent "
              f"to match, then re-run this script. First few:")
        for rel in stale_badges[:5]:
            print(f"  - {rel}")

    if stale_core:
        print(f"\nERROR: {len(stale_core)} page(s) are out of date with "
              f"partials/nav.html or partials/footer.html:")
        for rel in stale_core:
            print(f"  - {rel}")
        print("\nFix with:  python3 tools/build-nav.py")
        return 1

    print("All pages match the partials.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
