name: Deploy to S3 + CloudFront

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::082827114873:role/github-actions-dmi-deploy
          aws-region: us-east-1

      - name: Sync to S3
        run: |
          aws s3 sync . s3://dmi.pravinmishra.com \
            --region eu-west-1 \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "*.md" \
            --exclude "partials/*" \
            --exclude "tools/*" \
            --cache-control "public, max-age=300" \
            --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2N4UG9MOMV660 \
            --paths "/*"
